travis:
  secure:
    BINSTAR_TOKEN: racBcASXoEGnSgCQXDleQsYFLAyK01hCbbdjicc2p6Lj0XoVppV5pjnKRoNKjyhA6MSGCd5IfVxB0A8TK1FpaAFhURwsqj1s4pgG5NMpxBQy2WXJuGxUTHEktn5yHGcHM+MUzxP5/cDF6dwj430TkCa8lwmKb6V6ECbXtxinxH4LGYkuQhEvrsF5HbRJmE/+jhEgOZ/JVp0t1dbjFYe1L1luaBjqZDirHx9d4WXA6I6fvarq4qXTGETK6c3VW9wu0Yu3QqjnDAVbXuuTJQknxgrEYINEcUTSWIIBHVVy2j5zj42cKcfM4avS0+2FDGGO1mUouc6DCACsj8oUeTPuSw02FeyaBp+qogDNZdctva2KkCiGBgnIt7fFMcN6LSpW/GayMsVYGbAW8voOG0A8SncPIqpRy70X9hpAwqNDTUyOYdrUhTmcf+0DvEQPVW/qDKcBhfCBqHsX/p8JXTpFysMk1pbLdsAboCt8tB9gArXxB2EB6XcsxVGoF14rdDV6EzMU2z8Xuxx+Ngrl+SiR1LLGGCXwHJ0oEki/NDSgdGMElJB79wcPBFs5uDv0GtC1uDtuC504rhMOhytGdnW1DLDkCh6iAN1SyddfDJ8p9BoYJZFG4pxixC67h+okXuaLaFnnOH95Vjoz7fY5+3V7FqGOfagtW3C3yhe1Ik5qPog=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
